version: '3.3'

services:
  nextjs:
    image: ${IMAGE}:${TAG}
    container_name: node-${PROJECT}
    environment:
      - VIRTUAL_HOST=${PROJECT}.${STAGE}.gallit.net 
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${PROJECT}.${STAGE}.gallit.net
    networks:
      - default

