name: Deploy example app

on: 
  workflow_dispatch:
    inputs:
      environmemt:
        description: 'Deployment environment'
        required: true 
        default: 'dev'
        type: choice 
        options:
          - dev 
          - stage 
          - prod
      image: 
        description: 'Image name'
        type: string
        required: true 
        default: 'image'
      tag: 
        description: 'Image tag'
        type: string 
        required: false
        default: 'dev'
jobs:
  test_inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - working-directory: example_app/ansible
        run: | 
          echo "${{ secrets.VM_KEY }}" > inventory/key
          chmod 600 inventory/key
      - name: Run playbook 
        working-directory: example_app/ansible 
        run: ansible-playbook main.yml -i inventory