name: Deploy example app

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true 
        default: 'dev'
        type: choice 
        options:
          - dev 
          - stage 
          - prod
      image: 
        description: 'Image name'
        type: string
        required: true 
        default: 'image'
      region: 
        description: 'GCP region'
        required: true 
        type: string
      app_type: 
        description: 'Type of application'
        required: true
        type: choice 
        options:
          - frontend
          - backend
      tag: 
        description: 'Image tag'
        type: string 
        required: false
        default: 'dev'
jobs:
  test_inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./${{ inputs.image }}/ansible/main.yml
          # options: |
          #   -e project=${{ inputs.image }}
          #   -e region=${{ inputs.region }}
          #   -e app_type=${{ inputs.app_type }}
          #   -e env=${{ inputs.environment }}
      # - working-directory: example_app/ansible
      #   run: | 
      #     echo "${{ secrets.VM_KEY }}" > inventory/key
      #     chmod 600 inventory/key
      # - name: Run playbook 
      #   working-directory: example_app/ansible 
      #   run: | 
      #     export ANSIBLE_HOST_KEY_CHECKING=False
      #     cat  ../terraform/${{ inputs.environment }}/${{ inputs.app_type }}/locals.tf